### ISSUE TITLE
안녕하세요, 큰 파일 업로드가 안돼서 이슈로 등록합니다

### ISSUE THREAD

**Issue by jaehee329** [woowacourse-teams/2023-dong-gle#209]
### ⏰ Estimated Time

모르겠네요

### 🛠️ Description

안녕하세요, 
용량 25.7MB짜리 md파일을 업로드하니 아래와 같은 흐름으로 에러가 발생합니다

1. 업로드 시

<img width="1439" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/77962265/a40cede3-177e-4b19-8c80-1404b624751f">

2. 한참 뒤에 예외가 발생

<img width="1439" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/77962265/c94ec5da-a23d-4988-8346-afc47ce81157">

3. 이런 에러가 발생하네요

<img width="1439" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/77962265/74311357-0fcc-4950-bede-8bee884efabb">

### ✅ Tasks

예외에 대한 핸들링 혹은 파일에 대한 용량 선제검사를 하는 방법은 없을까요?

### 📝 Note

동글 화이팅
md파일은 용량이 커서 깃허브에 업로드가 안 되네요!
비버 블로그에 글 등록하지는 않았습니다

**Comment by yogjin** [comment]
제보 감사합니다🙂
