### ISSUE TITLE
JSX 태그 버그

### ISSUE THREAD

**Issue by nlom0218** [woowacourse-teams/2023-dong-gle#211]
### 어떤 버그인가요?

마크다운으로 `jsx` 코드를 작성하면 문법이 적용되지 않습니다.

### 예상 결과

```jsx
function App() {
  return <div>Hello World!</div>;
}
```

### 실제 결과

```js
function App() {
  return Hello World!;
}
```

### 스크린샷

원하는 결과
<img width="732" alt="스크린샷 2023-08-07 오후 1 45 45" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57981252/8f8611b5-dfac-4ffe-a29a-3a9825b04d23">

실제 결과
<img width="788" alt="스크린샷 2023-08-07 오후 1 45 36" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57981252/567f5cf4-f5f9-4aa2-ba6d-1c8ad456d000">

### 버그를 재현하는 법

JSX 문법이 존재하는 마크다운 파일을 업로드 했을 때 발생합니다.

### 어떤 환경에서 발생했나요?

- 브라우저 및 버전:
- 기기 및 OS:

**Comment by yogjin** [comment]
코드 블럭에서도 태그가 그대로 렌더링되는 문제가 있네요..
`<` `>` 등 문자를 `&lt` `&gt` 와 같은 이스케이프 문자로 변환하는 작업을 추가해야겠네요.
제보 감사합니다🙂
