### ISSUE TITLE
티스토리 연결 안됨

### ISSUE THREAD

**Issue by Hawardshin** [woowacourse-teams/2023-dong-gle#614]
### ⏰ Estimated Time

x

### 🛠️ Description

https://notice.tistory.com/2664

현재 티스토리로 업로드가 안되서 삭제후 다시 하려 했는데 아에 동작을 하지 않습니다.
해당 API종료와 연관이 있는지 궁금합니다.

### ✅ Tasks

감사합니다.

**Comment by yogjin** [comment]
넵 맞습니다. 
api지원 종료로 인해 티스토라 기능 제공이 막히게 되었습니다ㅠ
알려주셔서 감사하고 곧 공지올리겠습니다.
